# Generated by Django 3.2.12 on 2022-02-16 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_db_logger', '0002_auto_20190109_0052'),
    ]

    operations = [
        migrations.AddField(
            model_name='statuslog',
            name='details',
            field=models.JSONField(help_text='Additional info about the log (e.g. GET request path and query params).', null=True, verbose_name='details'),
        ),
    ]
