language: python

python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"

env:
  - DJANGO=1.6
  - DJANGO=1.7

matrix:
  exclude:
    - env: DJANGO=1.7
      python: "2.6"

install:
  - pip install Django==$DJANGO

script: python manage.py test