language: python

python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"

env:
  - DJANGO=1.6
  - DJANGO=1.7
  - DJANGO=1.8
  - DJANGO=1.9

matrix:
  exclude:
    - env: DJANGO=1.7
      python: "2.6"
    - env: DJANGO=1.8
      python: "2.6"
    - env: DJANGO=1.9
      python: "2.6"
    - env: DJANGO=1.9
      python: "3.3"

install:
  - pip install Django==$DJANGO

script: python manage.py test
