language: python

python:
  - "2.7"
  - "3.6"
  - "3.7"
  - "3.8"

env:
  - DJANGO=1.9
  - DJANGO=2.0
  - DJANGO=2.2
  - DJANGO=3.0

matrix:
  exclude:
    - env: DJANGO=1.9
      python: "3.3"

install:
  - pip install Django==$DJANGO

script: python test_manage.py test
