language: python

python:
  - "2.7"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"

env:
  - DJANGO=1.9
  - DJANGO=1.10
  - DJANGO=1.11.17
  - DJANGO=2.0
  - DJANGO=2.2
  - DJANGO=3.1
  - DJANGO=3.2

matrix:
  exclude:
    - env: DJANGO=2.0
      python: "2.7"
    - env: DJANGO=2.2
      python: "2.7"
    - env: DJANGO=3.1
      python: "2.7"
    - env: DJANGO=3.2
      python: "2.7"
    - env: DJANGO=1.9
      python: "3.8"
    - env: DJANGO=1.10
      python: "3.8"
    - env: DJANGO=1.9
      python: "3.9"
    - env: DJANGO=1.10
      python: "3.9"

install:
  - pip install Django==$DJANGO

script: python test_manage.py test
