from django.conf import settings

MSG_STYLE_SIMPLE = 'Simple'
MSG_STYLE_FULL = 'Full'

DJANGO_DB_LOGGER_ADMIN_LIST_PER_PAGE = getattr(settings, 'DJANGO_DB_LOGGER_ADMIN_LIST_PER_PAGE', 10)

DJANGO_DB_LOGGER_ENABLE_FORMATTER = getattr(settings, 'DJANGO_DB_LOGGER_ENABLE_FORMATTER', False)

DJANGO_DB_LOGGER_REQUEST_DETAILS = getattr(settings, 'DJANGO_DB_LOGGER_REQUEST_DETAILS', False)
DJANGO_DB_LOGGER_REQUEST_DETAILS_PATH = getattr(settings, 'DJANGO_DB_LOGGER_REQUEST_DETAILS_PATH', False)
DJANGO_DB_LOGGER_REQUEST_DETAILS_METHOD = getattr(settings, 'DJANGO_DB_LOGGER_REQUEST_DETAILS_METHOD', False)
DJANGO_DB_LOGGER_REQUEST_DETAILS_GET_PARAMS = getattr(settings, 'DJANGO_DB_LOGGER_REQUEST_DETAILS_GET_PARAMS', False)
DJANGO_DB_LOGGER_REQUEST_DETAILS_POST_PARAMS = getattr(settings, 'DJANGO_DB_LOGGER_REQUEST_DETAILS_POST_PARAMS', False)
